spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: olgaolga
    url: jdbc:mysql://localhost:3306/softclass?useUnicode=true&serverTimezone=UTC
    username: root
  jpa:
    database: mysql
#    show-sql=true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        globally_quoted_identifiers: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
