version: "3"
services:
  softclass-mysql-server:
    image: mysql
    networks:
      - softclass-app-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=postgres
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_HOST=%

  softclass-application:
    image: softclass-application
    ports:
      - "8080:8080"
    networks:
      - softclass-app-mysql
    depends_on:
      - softclass-mysql-server
    environment:
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_PROTOCOL=${MAIL_PROTOCOL}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - S3_ACCESSKEY=${S3_ACCESSKEY}
      - S3_SECRETKEY=${S3_SECRETKEY}
      - OAUTH2_GOOGLE_ID=${OAUTH2_GOOGLE_ID}
      - OAUTH2_GOOGLE_SECRET=${OAUTH2_GOOGLE_SECRET}
    entrypoint: ["./wait-for-it.sh", "softclass-mysql-server:3306", "-t", "20", "--", "java","-jar","app.jar"]

networks:
  softclass-app-mysql: